name: iron
description: A Music App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  marquee: ^2.2.3
  flutter_screenutil: ^5.8.4
  permission_handler: ^10.4.3
  drop_shadow: ^0.1.0
  scrollable_positioned_list: ^0.3.8
  dismissible_page: ^1.0.2
  cached_network_image: ^3.2.3
  # audio
  audio_video_progress_bar: ^1.0.1
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.10
  audio_service: ^0.18.10
  audio_session: ^0.1.16
  flutter_lyric: ^2.0.4+6
  # 获取媒体信息
  flutter_media_metadata: ^1.0.0+1
  flash: ^3.0.5+1
  motion_toast:
    git: https://github.com/koukibadr/Motion-Toast.git
  flutter_overlay_loader: ^2.0.0
  dio: ^5.3.2
  file_picker: ^5.3.3
  flutter_native_splash: ^2.3.2
  # 列表动画
  # flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/music/
    - assets/images/
    - assets/images/icon/

  fonts:
    - family: NotoSerifSC
      fonts:
        - asset: assets/fonts/NotoSerifSC-Black.otf
          weight: 900
        - asset: assets/fonts/NotoSerifSC-Bold.otf
          weight: 800
        - asset: assets/fonts/NotoSerifSC-Regular.otf
        - asset: assets/fonts/NotoSerifSC-SemiBold.otf
